# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [11]:
# Create a 1-dimensional NumPy array using np.array()
_1D = np.array([1,2,3,4,5])
# Create a 2-dimensional NumPy array using np.array()
_2D = np.array([[2,4,5,6,7,8],[2,3,5,2,1,35]])
# Create a 3-dimensional Numpy array using np.array()
_3D = np.array([[[2,4,5,6,7,8],[2,3,5,2,1,35],[2,3,5,2,1,35]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
_1D.shape, _1D.ndim, _1D.dtype, _1D.size

((5,), 1, dtype('int32'), 5)

In [8]:
# Attributes of 2-dimensional array
_2D.shape, _2D.ndim, _2D.dtype, _2D.size

((2, 6), 2, dtype('int32'), 12)

In [12]:
# Attributes of 3-dimensional array
_3D.shape, _3D.ndim, _3D.dtype, _3D.size

((1, 3, 6), 3, dtype('int32'), 18)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
_2DF = pd.DataFrame(_2D)

In [23]:
# Create an array of shape (10, 2) with only ones
tenTwo = np.ones((10,2))
tenTwo

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
# Create an array of shape (7, 2, 3) of only zeros
sevenTwoThree = np.zeros((7,2,3))
sevenTwoThree

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# Create an array within a range of 0 and 100 with step 3
zeroToOnehundred = np.arange(0,100,3)
zeroToOnehundred

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [25]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
zeroToTen = np.random.randint(0,10,size=(7,2))
zeroToTen

array([[5, 6],
       [5, 7],
       [9, 7],
       [7, 0],
       [7, 3],
       [2, 1],
       [9, 8]])

In [27]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
zeroToOne = np.random.randint(0,1,size=(3,5))
zeroToOne

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
zeroToTen2 = np.random.randint(0,10,size=(4,6))
zeroToTen2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [36]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
oneToTen2 = np.random.randint(1,10,size=(3,7))
oneToTen2
# Find the unique numbers in the array you just created
np.unique(oneToTen2)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [37]:
# Find the 0'th index of the latest array you created
oneToTen2[0]

array([9, 7, 9, 8, 2, 1, 7])

In [38]:
# Get the first 2 rows of latest array you created
oneToTen2[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [39]:
# Get the first 2 rows of latest array you created
oneToTen2[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [40]:
# Get the first 2 values of the first 2 rows of the latest array
oneToTen2[:2,:2]

array([[9, 7],
       [7, 8]])

In [50]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
oneToTenOne = np.random.randint(0,10,size=(3,5))
oneOnes = np.ones((3,5))
oneToTenOne


array([[1, 5, 6, 4, 0],
       [0, 2, 1, 4, 9],
       [5, 6, 3, 6, 7]])

In [51]:
oneOnes

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# Add the two arrays together
oneToTenOne + oneOnes

array([[ 2.,  6.,  7.,  5.,  1.],
       [ 1.,  3.,  2.,  5., 10.],
       [ 6.,  7.,  4.,  7.,  8.]])

In [53]:
# Create another array of ones of shape (5, 3)
oneOnes2 = np.ones((5,3))
oneOnes2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
# Try add the array of ones and the other most recent array together
oneOnes + oneOnes2.reshape(5,3,1)

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [56]:
# Create another array of ones of shape (3, 5)
oneOnes3 = np.ones((3,5))

In [58]:
# Subtract the new array of ones from the other most recent array
oneOnes3-oneOnes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
# Multiply the ones array with the latest array
oneOnes * oneOnes3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
# Take the latest array to the power of 2 using '**'
randNums = np.random.randint(0,10, size=(3,5))
randNums ** 2

array([[25, 25,  0, 64, 25],
       [ 4,  9,  9,  4, 81],
       [ 4,  4,  9, 36,  9]], dtype=int32)

In [63]:
# Do the same thing with np.square()
np.square(randNums)

array([[ 0, 25, 49],
       [16,  9,  1]], dtype=int32)

In [64]:
# Find the mean of the latest array using np.mean()
np.mean(randNums)

3.3333333333333335

In [65]:
# Find the maximum of the latest array using np.max()
np.max(randNums)

7

In [66]:
# Find the minimum of the latest array using np.min()
np.min(randNums)

0

In [67]:
# Find the standard deviation of the latest array
np.std(randNums)

2.357022603955158

In [68]:
# Find the variance of the latest array
np.var(randNums)

5.5555555555555545

In [71]:
# Reshape the latest array to (3, 5, 1)
randNums.reshape(3,5,1)

array([[[5],
        [5],
        [0],
        [8],
        [5]],

       [[2],
        [3],
        [3],
        [2],
        [9]],

       [[2],
        [2],
        [3],
        [6],
        [3]]])

In [72]:
# Transpose the latest array
randNums.T

array([[5, 2, 2],
       [5, 3, 2],
       [0, 3, 3],
       [8, 2, 6],
       [5, 9, 3]])

What does the transpose do?

In [73]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1=np.random.randint(0,10,size=(3,3))
arr2=np.random.randint(0,10,size=(3,2))

In [74]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

array([[ 50, 111],
       [ 57, 101],
       [120,  88]])

In [75]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1=np.random.randint(0,10,size=(4,3))
arr2=np.random.randint(0,10,size=(4,3))

In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2.T)

array([[25, 61, 65, 65],
       [30,  5,  7, 27],
       [82, 62, 46, 86],
       [36, 54, 62, 72]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [78]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1=np.random.randint(0,10,size=(4,4))
arr2=np.random.randint(0,10,size=(4,4))

In [79]:
# Compare the two arrays with '>'
arr1>arr2

array([[ True, False, False,  True],
       [False,  True,  True,  True],
       [False, False, False,  True],
       [False, False,  True, False]])

What happens when you compare the arrays with `>`?

In [80]:
# Compare the two arrays with '>='
arr1>=arr2

array([[ True,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True, False,  True],
       [False, False,  True, False]])

In [81]:
# Find which elements of the first array are greater than 7
arr1>7

array([[False, False, False,  True],
       [False,  True, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [82]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [83]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[2, 3, 7, 8],
       [1, 1, 2, 8],
       [1, 2, 5, 8],
       [0, 0, 3, 3]])

In [85]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)

array([[2, 1, 0, 3],
       [2, 3, 0, 1],
       [0, 2, 1, 3],
       [1, 3, 0, 2]], dtype=int64)

In [86]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr1)

3

In [87]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)

13

In [88]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)

array([3, 1, 3, 0], dtype=int64)

In [89]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1,axis=0)

array([2, 3, 1, 3], dtype=int64)

In [90]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-0.14089855,  0.87216186,  1.30034515, -1.34352376,  0.85012058],
       [ 0.39433995, -0.00469599, -1.57081198,  1.47984878,  0.39677428],
       [-1.78325106, -0.24313446,  0.32722339,  0.5065753 , -0.12760479]])

In [92]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.